In [45]:
import pandas as pd
import re

# collect data
df2 = pd.read_csv("C:/Users/milon/Downloads/Untitled form.csv")

# root data
#df1 = pd.read_excel("C:/Users/milon/Downloads/ml7.xlsx")

In [50]:
data_2 = df2["ID"]

#sorted data 2
data_2 = sorted(data_2)


# object to string

data_1 = df1["ID"].tolist()
data_2 = df2["ID"].tolist()

#upper case

# # data_2.upper()
# [x.upper() for x in data_2]

data_2 = [x.upper() for x in data_2]

data_2 = [x.strip(' ') for x in data_2]

type(data_1)
data_2

['16CSE038',
 '16CSE004',
 '16CSE032',
 '16CSE046',
 '16CSE039',
 '16CSE029',
 '16CSE056',
 '16CSE070',
 '16CSE059',
 '16CSE010',
 '16CSE037',
 '15CSE044',
 '16CSE057',
 '16CSE047',
 '16CSE020',
 '16CSE011',
 '16CSE031',
 '16CSE050',
 '15CSE020',
 '16CSE035',
 '16CSE014',
 '16CSE034',
 '16CSE005',
 '15CSE023',
 '16CSE068',
 '16CSE041',
 '16CSE049',
 '16CSE062',
 '16CSE012',
 '16CSE008',
 '16CSE065',
 '16CSE053',
 '16CSE028',
 '16CSE027',
 '16CSE051',
 '16CSE066',
 '16CSE048',
 '16CSE022',
 '15CSE030',
 '15CSE022',
 '16CSE052',
 '16CSE023',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0']

In [51]:
# print(type(data_2))
# print(type(data_1))

# data_2[:]

In [52]:
# # Using map function
# data_2 = map(lambda x:x.lower(), data_2[:])

In [58]:
i = 0
x= False
count = 0
for i in range(66):
    for k in range(66):
        if data_1[i] == data_2[k]:
            x = True #             print(data_1[i],"    1")
            count = count + 1
            break
        else:
            x = False
    if(x == True):
        print("1")
    else:
        print("0")
   # print(i," 0")
print(count)

0
0
0
1
1
0
1
1
1
1
1
0
0
0
1
0
1
1
0
0
0
1
1
1
0
1
1
1
1
0
1
1
1
0
1
0
1
1
1
1
1
1
1
1
0
1
1
0
1
0
0
1
0
1
1
1
1
0
1
1
1
1
1
0
0
0
42